#!/bin/bash -e

cd ChildrenAndYouth
yarn && yarn bundle-js
cd ../Curriculum
yarn && yarn bundle-js
cd ../Mobile
yarn && yarn bundle-js
cd ../Online
yarn && yarn bundle-js
cd ../Public
yarn && yarn bundle-js
cd ../Service
yarn && yarn bundle-js
cd ..

#mkdir builds
cp ChildrenAndYouth/builds/ChildrenAndYouth.min.js builds
cp Curriculum/builds/Curriculum.min.js builds
cp Mobile/builds/Mobile.min.js builds
cp Online/builds/Online.min.js builds
cp Public/builds/Public.min.js builds
cp Service/builds/GCSC.min.js builds
